services:
  quotations-db:
    container_name: quotations-psql
    image: postgres:16.1
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}